name: Run Scraper

on:
  schedule:
    - cron: '*/15 22-23 * * *'  # 10:00 PM – 11:59 PM UTC (3 PM – 4:59 PM MST)
    - cron: '*/15 0-5 * * *'    # 12:00 AM – 5:59 AM UTC (5 PM – 10:59 PM MST)
  workflow_dispatch:            # Manual runs via GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Clean node_modules
        run: rm -rf node_modules
        
      - name: Clean node_modules
        run: rm -rf node_modules
      - name: Install dependencies
        run: npm install

      - name: Debug Puppeteer path
        run: |
          node -e "console.log('Puppeteer version:', require('puppeteer/package.json').version)"
          node -e "console.log('Executable path:', require('puppeteer').executablePath?.())"

      - name: Debug Puppeteer path
        run: |
          node -e "console.log('Puppeteer version:', require('puppeteer/package.json').version)"
          node -e "console.log('Executable path:', require('puppeteer').executablePath?.())"

      - name: Run scraper
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: node index.js
